stages:
    - build
    - deploy

build_backend:
    stage: build
    image:  maven:3.9-amazoncorretto-19
    script:
        - cd Backend
        - echo "Building app..."
        - mvn clean install
        - echo "Finished building the app."
    artifacts:
        paths: 
            - Backend/target/ovniric-0.0.1-SNAPSHOT.jar
        expire_in: 1 week
        

deploy_backend:
    stage: deploy
    image: ubuntu:22.04
    before_script:
        -sudo apt-get update
        -sudo apt-get upgrade
        -sudo apt-get install openssh-client
    script:
        -ssh i $AWS_SECRET_ACCESS_KEY ubuntu@18.220.89.28
        -yes
        -sudo systemctl stop ovniric
        -sudo rm artifacOvniric/ovniric-0.0.1-SNAPSHOT.jar
        -logout
        -scp -i $AWS_SECRET_ACCESS_KEY Backend/target/ovniric-0.0.1-SNAPSHOT.jar ubuntu@18.220.89.28:/home/ubuntu/artifacOvniric/
        -ssh -i $AWS_SECRET_ACCESS_KEY ubuntu@18.220.89.28
        -sudo systemctl daemon-reload
        -sudo systemctl start ovniric
