stages:
    - build
    #- deploy

build_backend:
    stage: build
    image:  maven:3.8.6-openjdk-18
    script:
        - cd Backend
        - echo "Building app..."
    artifacts:
        expire_in: 1 week
        paths:
            - Backend/target/ovniric-0.0.1-SNAPSHOT.jar