stages:
    - build
    - deploy

build_backend:
    stage: build
    image:  maven:3.8.6-openjdk-18
    script:
        - cd Backend
        - echo "Building app..."
        - mvn clean install
        - echo "Finished building the app."
    artifacts:
        expire_in: 1 week
        paths:
            - Backend/target/PI-0.0.1-SNAPSHOT.jar
    rules:
        - changes: 
            - Backend/**/*

deploy_Backend:
    stage: deploy
    needs: [build_backend]
    image: alpine:3.11
    before_script:
        - apk update && apk add openssh-client bash
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        - touch ~/.ssh/config
        - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        - ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
    script:
        - echo "Deploying started..."
        - ssh ubuntu@$SERVER_IP "sudo systemctl stop ovniric.service"
        - scp Backend/target/PI-0.0.1-SNAPSHOT.jar ubuntu@$SERVER_IP:~/artifacOvniric/
        - ssh ubuntu@$SERVER_IP "sudo systemctl start ovniric.service"
        - echo "Finished deploying the app."
    rules:
        - changes: 
            - Backend/**/*    
    